### ISSUE TITLE
If somebody removes their !echo message the bot should also remove its response

### ISSUE THREAD

**Issue by elihschiff** [rpi-cs-discord/Rubber-Duck#19]

**Comment by benjaminrsherman** [comment]
The best way to go about this is probably to iterate through messages after the deleted message until a specific time period has passed.  I'm unsure if this is possible via the discord.js api, however.  It may be necessary to create a file which logs all echoes.

**Comment by iEli2tyree011** [comment]
Alternatively, listen for the message deleted event, and fetch any nearby messages when that event is called (which is possible using discord.js).

**Comment by elihschiff** [comment]
@iEli2tyree011 That is what I did. Thanks for the suggestion.
