### ISSUE TITLE
Add fuzzy search for adding classes 

### ISSUE THREAD

**Issue by elihschiff** [rpi-cs-discord/Rubber-Duck#23]
Adding classes should fuzzy search instead of direct match

**Comment by elihschiff** [comment]
https://www.npmjs.com/package/fuse.js

**Comment by chrisj1** [comment]
Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn't very fuzzy anymore.

**Comment by chrisj1** [comment]
WHAT HAPPENED!
