### ISSUE TITLE
Per user emoji-only mode

### ISSUE THREAD

**Issue by benjaminrsherman** [rpi-cs-discord/Rubber-Duck#7]
Emoji-only mode is a useful tool for both moderation and memes.  Allowing it to be activated for a single account would support those goals while not derailing a channel.

**Comment by elihschiff** [comment]
Do we want the option to do both a specific channel as well as server wide?

**Comment by benjaminrsherman** [comment]
Possible methods: storing a list of users which are in this mode, or granting a role which places someone in emoji-only mode

**Comment by benjaminrsherman** [comment]
@elihschiff more granularity is probably better.

**Comment by elihschiff** [comment]
I was going to do the role at first but I realized that is server wide so I guess I can just save it per user per channel. I also should probably add a remove all command for a specific user

**Comment by benjaminrsherman** [comment]
Perhaps the role can be used for server-wide implementation, coupled with a channel-specific user list for per-channel implementation.
